version: '3.8'
services:
  redis:
    container_name: redis
    image: redis:7.0-alpine3.16
    ports:
      - '6379:6379'
  jaeger:
    container_name: jaeger
    image: 'jaegertracing/all-in-one:1.38'
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"